# Generated by Django 2.0.1 on 2018-01-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='name',
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='first_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
